In [1]:
import pandas as pd
import numpy as np

this is my *notes*

In [2]:
total_df = pd.read_csv('./data_gathering/imdb_ratings.csv')
total_df = total_df.loc[total_df["budget"].notna()]
total_df = total_df.loc[total_df["budget"] != np.float64(0.0)]
total_df = total_df.loc[total_df["global_revenue"].notna()]
total_df = total_df.loc[total_df["global_revenue"] != np.float64(0.0)]
total_df = total_df.rename(columns={"global_revenue":"revenue"})
total_df = total_df.set_index("title")
total_df

,runtime,genre,averageRating,release_date,budget,revenue
title,,,,,,
Star Wars Ep. VII: The Force Awakens,NaN,NaN,NaN,"Dec 16, 2015",533200000.0,2.056047e+09
Avatar: The Way of Water,192,"Action,Adventure,Fantasy",7.5,"Dec 9, 2022",460000000.0,2.317514e+09
Indiana Jones and the Dial of Destiny,154,"Action,Adventure,Sci-Fi",6.5,"Jun 28, 2023",402300000.0,3.839631e+08
Avengers: Endgame,181,"Action,Adventure,Drama",8.4,"Apr 23, 2019",400000000.0,2.748243e+09
Pirates of the Caribbean: On Stranger Tides,136,"Action,Adventure,Fantasy",6.6,"May 20, 2011",379000000.0,1.045714e+09
...,...,...,...,...,...,...
Cavite,80,"Crime,Drama,Thriller",6.0,"May 26, 2006",7000.0,7.164400e+04
The Mongol King,NaN,NaN,NaN,Unknown,7000.0,9.000000e+02
Following,69,"Crime,Mystery,Thriller",7.4,"Apr 2, 1999",6000.0,2.404950e+05
Return to the Land of Wonders,88,"Documentary,War",6.9,"Jul 13, 2005",5000.0,1.338000e+03
My Date With Drew,NaN,NaN,NaN,"Aug 5, 2005",1100.0,1.810410e+05

In [3]:
profit_col = []
for i in total_df.index:
    profit_col.append(total_df.loc[i, "revenue"] - total_df.loc[i, "budget"])
profit_col = pd.DataFrame({"profit":profit_col})
profit_col = profit_col.set_index(total_df.index)
total_df = pd.concat([total_df, profit_col], axis=1)
total_df

,runtime,genre,averageRating,release_date,budget,revenue,profit
title,,,,,,,
Star Wars Ep. VII: The Force Awakens,NaN,NaN,NaN,"Dec 16, 2015",533200000.0,2.056047e+09,1.522847e+09
Avatar: The Way of Water,192,"Action,Adventure,Fantasy",7.5,"Dec 9, 2022",460000000.0,2.317514e+09,1.857514e+09
Indiana Jones and the Dial of Destiny,154,"Action,Adventure,Sci-Fi",6.5,"Jun 28, 2023",402300000.0,3.839631e+08,-1.833694e+07
Avengers: Endgame,181,"Action,Adventure,Drama",8.4,"Apr 23, 2019",400000000.0,2.748243e+09,2.348243e+09
Pirates of the Caribbean: On Stranger Tides,136,"Action,Adventure,Fantasy",6.6,"May 20, 2011",379000000.0,1.045714e+09,6.667138e+08
...,...,...,...,...,...,...,...
Cavite,80,"Crime,Drama,Thriller",6.0,"May 26, 2006",7000.0,7.164400e+04,6.464400e+04
The Mongol King,NaN,NaN,NaN,Unknown,7000.0,9.000000e+02,-6.100000e+03
Following,69,"Crime,Mystery,Thriller",7.4,"Apr 2, 1999",6000.0,2.404950e+05,2.344950e+05
Return to the Land of Wonders,88,"Documentary,War",6.9,"Jul 13, 2005",5000.0,1.338000e+03,-3.662000e+03
My Date With Drew,NaN,NaN,NaN,"Aug 5, 2005",1100.0,1.810410e+05,1.799410e+05

In [ ]:
horror_df = pd.read_excel("./csv_input/horror_movies.xlsx")
horror_df